import os
import json
import random
import sys
from io import BytesIO
from datetime import datetime
import google.generativeai as genai
from stability_sdk import client
import stability_sdk.interfaces.gooseai.generation.generation_pb2 as generation

# --- Configuration & API Keys ---
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
STABILITY_API_KEY = os.getenv("STABILITY_API_KEY")
JSON_FILE = 'dreams.json'
IMAGE_DIR = 'generated_images'

# --- Dynamic Prompt Generation ---
SUBJECTS = [
    "a geothermal lagoon under a sky of stars", "a library carved from glacial ice",
    "a Viking longship sailing the aurora borealis", "a lighthouse at the edge of the world",
    "a rune-carved stone humming with power", "the heart of a sleeping volcano"
]
CONCEPTS = [
    "a forgotten saga", "the memory of the first winter", "the silence between worlds",
    "the solitude of the midnight sun", "an echo from a dying star"
]
STYLES = [
    "as a lost myth", "whispered by the arctic wind", "etched in volcanic rock",
    "as a prophecy", "as a sailor's final log entry"
]

def generate_creative_prompt():
    subject = random.choice(SUBJECTS)
    concept = random.choice(CONCEPTS)
    style = random.choice(STYLES)
    return f"{subject}, about {concept}, {style}"

# --- AI Interaction (Gemini) ---
def generate_poem_and_image_prompt(initial_prompt):
    genai.configure(api_key=GEMINI_API_KEY)
    model = genai.GenerativeModel('gemini-1.5-flash')
    
    # Generate Poem and explicitly cast to string
    poem_response = model.generate_content(f"You are the Skald... Write a short poem based on this idea: '{initial_prompt}'.")
    poem = str(getattr(poem_response, 'text', ''))
    print(f"--- Generated Poem ---\n{poem.strip()}\n----------------------")

    # Generate Image Prompt and explicitly cast to string
    image_prompt_template = f"Read this poem and transform it into a rich, detailed prompt for an AI image generator...\n\nPOEM:\n\"\"\"\n{poem}\n\"\"\"\n\nDETAILED PROMPT:"
    image_prompt_response = model.generate_content(image_prompt_template)
    image_prompt = str(getattr(image_prompt_response, 'text', ''))
    print(f"--- Generated Image Prompt ---\n{image_prompt.strip()}\n----------------------------")
    
    return poem, image_prompt

# --- Image Generation (Stability AI) ---
def generate_image(prompt):
    stability_api = client.StabilityInference(key=STABILITY_API_KEY, engine="stable-diffusion-xl-1024-v1-0")
    answers = stability_api.generate(prompt=[generation.Prompt(text=prompt)], height=1088, width=1920, steps=30, cfg_scale=7.0, samples=1)
    for resp in answers:
        for artifact in resp.artifacts:
            if artifact.finish_reason == generation.FILTER:
                raise Warning("Image generation failed due to safety filter.")
            if artifact.type == generation.ARTIFACT_IMAGE:
                print("Image generated successfully from Stability AI.")
                return BytesIO(artifact.binary)
    return None

# --- File Operations ---
def save_image_and_update_json(poem, image_bytes, initial_prompt):
    try:
        timestamp_str = datetime.utcnow().strftime('%Y-%m-%d_%H-%M-%S')
        image_filename = f"{timestamp_str}.png"
        image_path = os.path.join(IMAGE_DIR, image_filename)
        os.makedirs(IMAGE_DIR, exist_ok=True)
        
        with open(image_path, "wb") as f:
            f.write(image_bytes.read())
        print(f"Image saved to: {image_path}")

        with open(JSON_FILE, 'r+') as f:
            data = json.load(f)
            new_dream_entry = {
                "timestamp": str(datetime.utcnow().isoformat() + "Z"),
                "prompt": str(initial_prompt),
                "poem": str(poem).strip(),
                "image_url": str(image_path)
            }
            data['dreams'].append(new_dream_entry)
            f.seek(0)
            json.dump(data, f, indent=4)
            f.truncate()
    except TypeError as e:
        print(f"A TypeError occurred during file operations, likely with json.dump: {e}", file=sys.stderr)
        raise
    except Exception as e:
        print(f"An unexpected error occurred during file operations: {e}", file=sys.stderr)
        raise

# --- Main Execution ---
def main():
    if not all([GEMINI_API_KEY, STABILITY_API_KEY]):
        raise ValueError("Gemini or Stability API key is missing. Check your GitHub Secrets.")
    
    print("The Skald is waking...")
    initial_prompt = generate_creative_prompt()
    print(f"--- Initial Idea ---\n{initial_prompt}\n--------------------")
    
    poem, image_prompt = generate_poem_and_image_prompt(initial_prompt)
    
    if not poem or not poem.strip():
        raise ValueError("The poem generated by Gemini was empty. Halting run.")
    if not image_prompt or not image_prompt.strip():
        raise ValueError("The image prompt generated by Gemini was empty. Halting run.")

    image_bytes = generate_image(image_prompt)
    if image_bytes:
        save_image_and_update_json(poem, image_bytes, initial_prompt)
        print("A new dream has been recorded. The Skald sleeps again.")

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"An error occurred in the main process: {e}", file=sys.stderr)