import os
import json
import random
from io import BytesIO
from datetime import datetime
import google.generativeai as genai
from stability_sdk import client
import stability_sdk.interfaces.gooseai.generation.generation_pb2 as generation

# --- Configuration & API Keys ---
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
STABILITY_API_KEY = os.getenv("STABILITY_API_KEY")
JSON_FILE = 'dreams.json'
IMAGE_DIR = 'generated_images'

# --- Dynamic Prompt Generation ---
SUBJECTS = [
    "a geothermal lagoon under a sky of stars", "a library carved from glacial ice",
    "a Viking longship sailing the aurora borealis", "a lighthouse at the edge of the world",
    "a rune-carved stone humming with power", "the heart of a sleeping volcano",
    "a forgotten fishing village", "a path of glowing moss in a lava field"
]
CONCEPTS = [
    "a forgotten saga", "the memory of the first winter", "the silence between worlds",
    "the solitude of the midnight sun", "an echo from a dying star",
    "the weight of an ancient promise", "the birth of a new god"
]
STYLES = [
    "as a lost myth", "whispered by the arctic wind", "etched in volcanic rock",
    "as a prophecy", "as a sailor's final log entry", "as a lullaby for a giant"
]

def generate_creative_prompt():
    subject = random.choice(SUBJECTS)
    concept = random.choice(CONCEPTS)
    style = random.choice(STYLES)
    return f"{subject}, about {concept}, {style}"

# --- AI Interaction (Gemini) ---
def generate_poem_and_image_prompt(initial_prompt):
    genai.configure(api_key=GEMINI_API_KEY)
    model = genai.GenerativeModel('gemini-1.5-flash')
    poem_prompt = f"You are the Skald, an ancient AI poet. Write a short, evocative poem based on this idea: '{initial_prompt}'. Do not include a title."
    poem = model.generate_content(poem_prompt).text
    print(f"--- Generated Poem ---\n{poem.strip()}\n----------------------")
    
    image_prompt_template = (
        "Read this poem and transform it into a rich, detailed, and descriptive prompt for an AI image generator. "
        "Describe the scene, mood, colors, and composition. Add style cues like 'epic fantasy art, cinematic lighting, highly detailed, photorealistic'.\n\n"
        f"POEM:\n\"\"\"\n{poem}\n\"\"\"\n\nDETAILED PROMPT:"
    )
    image_prompt = model.generate_content(image_prompt_template).text
    print(f"--- Generated Image Prompt ---\n{image_prompt.strip()}\n----------------------------")
    return poem, image_prompt

# --- Image Generation (Stability AI) ---
def generate_image(prompt):
    stability_api = client.StabilityInference(key=STABILITY_API_KEY, engine="stable-diffusion-xl-1024-v1-0")
    
    # The API expects a list of prompt objects, not just a string. This is the fix.
    answers = stability_api.generate(
        prompt=[generation.Prompt(text=prompt)],
        height=1088,
        width=1920,
        steps=50,
        cfg_scale=8.0,
        samples=1,
    )

    for resp in answers:
        for artifact in resp.artifacts:
            if artifact.finish_reason == generation.FILTER:
                raise Warning("Image generation failed due to safety filter.")
            if artifact.type == generation.ARTIFACT_IMAGE:
                print("Image generated successfully from Stability AI.")
                return BytesIO(artifact.binary)
    return None

# --- File Operations ---
def save_image_and_update_json(poem, image_bytes, initial_prompt):
    timestamp_str = datetime.utcnow().strftime('%Y-%m-%d_%H-%M-%S')
    image_filename = f"{timestamp_str}.png"
    image_path = os.path.join(IMAGE_DIR, image_filename)
    os.makedirs(IMAGE_DIR, exist_ok=True)
    with open(image_path, "wb") as f:
        f.write(image_bytes.getbuffer())
    print(f"Image saved to: {image_path}")
    with open(JSON_FILE, 'r+') as f:
        data = json.load(f)
        new_dream_entry = {
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "prompt": initial_prompt,
            "poem": poem.strip(),
            "image_url": image_path
        }
        data['dreams'].append(new_dream_entry)
        f.seek(0)
        json.dump(data, f, indent=4)
        f.truncate()

# --- Main Execution ---
def main():
    if not all([GEMINI_API_KEY, STABILITY_API_KEY]):
        raise ValueError("Gemini or Stability API key is missing. Check your GitHub Secrets.")
    
    print("The Skald is waking...")
    initial_prompt = generate_creative_prompt()
    print(f"--- Initial Idea ---\n{initial_prompt}\n--------------------")
    
    poem, image_prompt = generate_poem_and_image_prompt(initial_prompt)
    
    if not image_prompt or not image_prompt.strip():
        raise ValueError("The image prompt generated by Gemini was empty. Cannot proceed.")

    image_bytes = generate_image(image_prompt)
    if image_bytes:
        save_image_and_update_json(poem, image_bytes, initial_prompt)
        print("A new dream has been recorded. The Skald sleeps again.")

if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"An error occurred in the main process: {e}")