name: Skald Daily Dream

on:
  schedule:
    - cron: '15 3 * * *'
  workflow_dispatch:

jobs:
  generate-dream:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # Fetch all history for all branches and tags. This is the new fix.
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai requests stability-sdk

      - name: Run the dream script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          STABILITY_API_KEY: ${{ secrets.STABILITY_API_KEY }}
        run: python scripts/generate_dream.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'Skald Bot'
          git config --global user.email 'actions@github.com'
          # Pull latest changes to avoid conflicts
          git pull --rebase
          # Add all new/modified files to the commit
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Skald dreamt a new dream"
          git push