name: Skald Daily Dream

on:
  schedule:
    - cron: '15 3 * * *'
  workflow_dispatch:

jobs:
  generate-dream:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade google-generativeai
          pip install requests

      - name: Run the dream script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          STABILITY_API_KEY: ${{ secrets.STABILITY_API_KEY }}
        run: python scripts/generate_dream.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'Skald Bot'
          git config --global user.email 'actions@github.com'
          
          # Stash the new files to get a clean working directory
          git stash
          
          # Pull the latest changes from the repository
          git pull --rebase
          
          # Apply the stashed changes back on top
          git stash pop
          
          # Now, add, commit, and push the new dream
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "Skald dreamt a new dream"
            git push
          else
            echo "No new dream was generated or an error occurred in the stash process."
          fi
