name: Skald Daily Dream

on:
  schedule:
    - cron: '15 3 * * *'
  workflow_dispatch:

jobs:
  generate-dream:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai requests stability-sdk

      - name: Debug API Keys
        run: |
          echo "Is GEMINI_API_KEY set? : ${{ env.GEMINI_API_KEY != '' }}"
          echo "Is STABILITY_API_KEY set? : ${{ env.STABILITY_API_KEY != '' }}"

      - name: Run the dream script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          STABILITY_API_KEY: ${{ secrets.STABILITY_API_KEY }}
        run: python scripts/generate_dream.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'Skald Bot'
          git config --global user.email 'actions@github.com'
          
          git fetch origin
          git reset --hard origin/main
          
          git add .
          
          if ! git diff --staged --quiet; then
            git commit -m "Skald dreamt a new dream"
            # Force push to overwrite the remote branch and break the lock.
            git push --force origin main
          else
            echo "No new dream was generated, nothing to commit."
          fi