name: Skald Daily Dream

on:
  # Run this workflow every day at 3:15 AM UTC
  schedule:
    - cron: '15 3 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate-dream:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This permission is necessary to commit changes back to the repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Specify Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai requests

      - name: Run the dream script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python scripts/generate_dream.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'Skald Bot'
          git config --global user.email 'actions@github.com'
          git add dreams.json
          # Commit only if there are changes
          git diff --quiet && git diff --staged --quiet || git commit -m "Skald dreamt a new dream"
          git push